### ISSUE TITLE
[Bug]: Building app in release mode cause fatal error

### ISSUE THREAD

**Issue by HarshitSingh1509** [apivideo/api.video-flutter-player#43]
### Version

1.0.0

### Environment that reproduces the issue

<img width="730" alt="image" src="https://github.com/apivideo/api.video-flutter-player/assets/66547034/6dc0d76a-e296-477e-a33c-cc5e1a2cf785">

### Is it reproducible in the example application?

Yes

### Reproduction steps

Just Run the app having video player using this command
flutter run --release

### Expected result

The app should Play the Videos

### Actual result

The App Crashes with the stack trace:
E/AndroidRuntime(22759): FATAL EXCEPTION: main
E/AndroidRuntime(22759): Process: com.*****.****, PID: 22759
E/AndroidRuntime(22759): yb.i: Serializer for class 'h' is not found.
E/AndroidRuntime(22759): Mark the class as @Serializable or provide the serializer explicitly.
E/AndroidRuntime(22759):        at cc.b1.d(Unknown Source:33)
E/AndroidRuntime(22759):        at cc.a1.k(Unknown Source:5)
E/AndroidRuntime(22759):        at yb.l.d(Unknown Source:22)
E/AndroidRuntime(22759):        at yb.k.b(Unknown Source:0)
E/AndroidRuntime(22759):        at ld.c.p(Unknown Source:42)
E/AndroidRuntime(22759):        at ld.c.l(Unknown Source:9)
E/AndroidRuntime(22759):        at hd.a.K(Unknown Source:32)
E/AndroidRuntime(22759):        at o2.p1.z2(Unknown Source:0)
E/AndroidRuntime(22759):        at o2.p1.m1(Unknown Source:0)
E/AndroidRuntime(22759):        at o2.e.invoke(Unknown Source:6)
E/AndroidRuntime(22759):        at q4.t$c.a(Unknown Source:17)
E/AndroidRuntime(22759):        at q4.t.h(Unknown Source:16)
E/AndroidRuntime(22759):        at q4.t.a(Unknown Source:0)
E/AndroidRuntime(22759):        at q4.s.run(Unknown Source:6)
E/AndroidRuntime(22759):        at q4.t.f(Unknown Source:69)
E/AndroidRuntime(22759):        at q4.t.l(Unknown Source:3)
E/AndroidRuntime(22759):        at o2.p1.b3(Unknown Source:7)
E/AndroidRuntime(22759):        at o2.p1.M(Unknown Source:10)
E/AndroidRuntime(22759):        at n2.a1.z2(Unknown Source:2)
E/AndroidRuntime(22759):        at n2.a1.O0(Unknown Source:0)
E/AndroidRuntime(22759):        at n2.c0.invoke(Unknown Source:4)
E/AndroidRuntime(22759):        at q4.t$c.a(Unknown Source:17)
E/AndroidRuntime(22759):        at q4.t.h(Unknown Source:16)
E/AndroidRuntime(22759):        at q4.t.a(Unknown Source:0)
E/AndroidRuntime(22759):        at q4.s.run(Unknown Source:6)
E/AndroidRuntime(22759):        at q4.t.f(Unknown Source:69)
E/AndroidRuntime(22759):        at n2.a1.X2(Unknown Source:432)
E/AndroidRuntime(22759):        at n2.a1.c2(Unknown Source:207)
E/AndroidRuntime(22759):        at n2.a1.h2(Unknown Source:0)
E/AndroidRuntime(22759):        at n2.a1.g1(Unknown Source:0)
E/AndroidRuntime(22759):        at n2.a0.run(Unknown Source:4)
E/AndroidRuntime(22759):        at android.os.Handler.handleCallback(Handler.java:942)
E/AndroidRuntime(22759):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(22759):        at android.os.Looper.loopOnce(Looper.java:240)
E/AndroidRuntime(22759):        at android.os.Looper.loop(Looper.java:351)
E/AndroidRuntime(22759):        at android.app.ActivityThread.main(ActivityThread.java:8416)
E/AndroidRuntime(22759):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(22759):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
E/AndroidRuntime(22759):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

### Additional context

The error is only producible in release mode

**Comment by ThibaultBee** [comment]
Hi,

There was an obfuscation issue on the analytics library. I made a fixes on the `main` branch. Could you test the example in the `main` branch to verify it is fixed?

**Comment by ThibaultBee** [comment]
A fix has been shipped with v1.1.0.
Could you check if the issue you are facing is fixed?

**Comment by HarshitSingh1509** [comment]
Yeah, I have applied, thankyou for quick response and resolving the issue
