### ISSUE TITLE
[Bug]: Pause button doesn’t show and player crashes on tap of screen 

### ISSUE THREAD

**Issue by Haroldkess** [apivideo/api.video-flutter-player#47]
### Version

apivideo_player: ^1.2.0

### Environment that reproduces the issue

Device [iPhone 8 plus] 

OS: [ 16.2]

### Is it reproducible in the example application?

No

### Reproduction steps

1. Use a pageview.builder with pagesnapping set to true. (Swipe through video just like TikTok). Items is a list of vodId gotten from our backend . 

2. Return a new widget in the pageview.builder  and parse the Vod Id to it let’s call the widget Videobox. 

3. Build your videoOptions on init of videobox and parse it to the  ApiVideoPlayerController  then  return a new widget called VideoPlay and parse this ApiVideoPlayerController to a new widget called VideoPlay . 

4. Initialize the controller oninit of videoplay add listeners(video should play onReady ) . And dispose ApiVideoPlayerController. 
5. Then tap your screen 

### Expected result

Pause button should show and I should be able to interact with it 

### Actual result

Pause button doesn’t show and The player crashes on tap of screen (anywhere on screen) which in turn crashes the app.

**Comment by ThibaultBee** [comment]
Hi,

As the way to reproduce the issue seems really specific, could you provide a sample code to test it?

Do you have the same issue with Android phones?

**Comment by Haroldkess** [comment]
You can close this

**Comment by ThibaultBee** [comment]
Do you mean it is fixed?

**Comment by Haroldkess** [comment]
I’m not able to provide a sample as I’m unavailable @work at the time.
Until a week from today. Would humbly appreciate if you could exercise some
patience until then

**Comment by ThibaultBee** [comment]
Of course!

**Comment by ThibaultBee** [comment]
Stalled issue -> closing.

Please reopen it if you have new info.
