### ISSUE TITLE
[Feat]: Duration for displaying Pause and play controls on screen should be controlled by developers 

### ISSUE THREAD

**Issue by Haroldkess** [apivideo/api.video-flutter-player#49]
### Version

apivideo_player: ^1.2.0

### Environment that reproduces the issue

All environments 

### Use case description

When player is initialized the pause, rewind and forward buttons are also displayed on screen, and if the screen is tapped it takes about 2 -4 seconds to dismiss these controls. 

### Proposed solution

Set a parsable variable for developers to select their choice of button dismissed delay on screen tap.

**Comment by ThibaultBee** [comment]
Hi,

Just to be 100% sure, you want to set the duration in which the buttons are displayed?

**Comment by Haroldkess** [comment]
Set a duration in which the button leaves the screen on tap of the screen.

**Comment by ThibaultBee** [comment]
Hi,

Could you verify that https://github.com/apivideo/api.video-flutter-player/pull/51 fit your expectations?

**Comment by Haroldkess** [comment]
Yeah that's great 👍🏽

**Comment by ThibaultBee** [comment]
Released in v1.2.1
