### ISSUE TITLE
[Bug]: player stops working on randomly with error.

### ISSUE THREAD

**Issue by DhruvinUnikon** [apivideo/api.video-flutter-player#57]
### Version

1.2.1

### Environment that reproduces the issue

same as #56.

### Is it reproducible in the example application?

Yes

### Reproduction steps

1. Create a tabular layout on the the flutter application .
2. In any of the tab add video player.
3. Switch between the tabs fast. 
4. Randomly it throws error. 
5. It stops working randomly. 

### Expected result

1. Shouldn't not throw any error and player should play video. 

### Actual result

- Here is the information about the crash [logs](https://gist.github.com/DhruvinUnikon/63ad58f55532e6c7319f0ece56be381d).

**Comment by ThibaultBee** [comment]
Hi,
It seems that the device can't initiate a new decoder probably because the other has not been closed.
Have you called `controller.dispose`?

**Comment by DhruvinUnikon** [comment]
Yes we are doing it, and is there any limit at time how many controllers we can keep?

**Comment by ThibaultBee** [comment]
This issue is coming from ExoPlayer. See https://github.com/google/ExoPlayer/issues/6168#issuecomment-1447753880
The number of hardware decoder will depend from one device to another.
If you are calling `dispose` and you get this issue it might be because the call to `ExoPlayer.release` is async.
Maybe just adding a debounce will suffice.

**Comment by DhruvinUnikon** [comment]
> Yes we are doing it, and is there any limit at time how many controllers we can keep?



> This issue is coming from ExoPlayer. See [google/ExoPlayer#6168 (comment)](https://github.com/google/ExoPlayer/issues/6168#issuecomment-1447753880) The number of hardware decoder will depend from one device to another. If you are calling `dispose` and you get this issue it might be because the call to `ExoPlayer.release` is async. Just adding a debounce might suffice.

Thanks @ThibaultBee for back reference.

**Comment by ThibaultBee** [comment]
Closing because there is not much we can do on our side.
Could you reopen the issue if you need more investigation?
